!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 268 $
!> $Author: dsu $
!> $Date: 2015-01-09 17:00:41 -0800 (Fri, 09 Jan 2015) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/constnts.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine constnts
!c -------------------
!c
!c assign constants for global use
!c
!c written by:      Uli Mayer - May 7, 96
!c
!c last modified:   Uli Mayer - November 19, 96
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   -
!c
!c common:   
!c gen.f:    real*8:
!c           ------- 
!c           sec_per_days       = conversion factor from SI input     * +
!c                                units for physico-chemical
!c                                parameters to internal time units
!c
!c           logical:
!c           -------- 
!c           geo_chemistry      = .true.  -> local or background and  + -
!c                                           source chemistry
!c 
!c local:    -
!c
!c external: gcconst  = assign constants for geochemistry
!c ----------------------------------------------------------------------

      subroutine constnts
 
      use parm
      use gen
      use phys

      implicit none

      external gcconst

!c  assign time conversion factor

      sec_per_days = 8.64d4

!c  assign constants for geochemistry

      if (geo_chemistry) then
        call gcconst
      end if
      
!c  assign gravity constant
      
      gacc = 9.80665d0
      
!c  assign viscosity of water
      visc_h2o = 1.0d-3
      
!c  assign density of water    
      dens_h2o = 1.0d+3

      return
      end
