!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 355 $
!> $Author: dsu $
!> $Date: 2015-07-10 14:10:57 -0700 (Fri, 10 Jul 2015) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/dual.F90 $
!---------------------------------------------------------------------
!********************************************************************!

      module dual

      use parm
      
      implicit none

!c ----------------------------------------------------------------------
!c common - dual porosity/permeability formulation
!c
!c ----------------------------------------------------------------------
!c        -->                                                         <--
!c           real*8:
!c           -------
!c           alpha_dp_fixed     = core paramters for dual permeability 
!c                                exchange term 
!c
!c           character:
!c           ----------
!c
!c           logical:
!c           -------- 
!c           dual_porosity      = .true.  -> dual porosity
!c                                           simulation
!c
!c        -->                                                         <--
!c ----------------------------------------------------------------------

      real (type_r8) :: alpha_dp_fixed
      
      real (type_r8) :: alpha_s_dp_fixed
      
      real (type_r8) :: alpha_g_dp_fixed

      logical :: dual_porosity
      
!c ----------------------------------------------------------------------
!c control parameters - dual permeability
!c ---------------------------------------
!c        -->                                                         <--
!c           real*8:
!c           -------
!c           beta_dp            = shape factor [-] that depends on 
!c                                the geometry,  e.g., 3.0d0
!c           gamma_dp           = scaling factor [-] obtained by 
!c                                matching the results of the 
!c                                first-order approach at the 
!c                                half-time level of the cumulative 
!c                                infiltration curve to the numerical
!c                                solution of the horizontal 
!c                                infiltration equation 
!c                                [Gerke and van Genuchten, 1993]
!c                                e.g., 0.4
!c           dist_dp            = effective 'diffusion' 
!c                                pathlength [m]
!c                                e.g., half the matrix width or 
!c                                half the fracture spacing, 0.01 m
!c           cond_ex_sat        = effective hydraulic conductivity 
!c                                [m/day], e.g., 1.0d-4 m/day
!c           w_fracture         = fracture proportion [-]
!c                                e.g., 0.5
!c           w_matrix           = matrix proportion [-]
!c                                equal to 1- w_fracture
!c                                e.g., 0.5
!c           diff_eff_dp        = effective 'diffusion' coefficient 
!c                                [m*m/day], e.g., 0.5d-4 m*m/day
!c           diff_eff_dp        = effective 'diffusion' coefficient 
!c                                for gas [m*m/day]
!c           mat_frac_face_y    = interface of matrix and fracture 
!c                                location in y-direction [m]
!c                                e.g., 0.5 m
!c
!c           integer:
!c           --------
!c
!c           logical:
!c           --------
!c           dual_permeability  = .true.  -> enable dual permeability
!c                                .false. -> disable dual permeability
!c           
!c           usage:
!c           ---------
!c
!c           ! Section 11B: physical parameters - dual permeability                      			
!c           ! --------------------------------------------------------------------------			
!c           !
!c           'physical parameters - dual permeability'
!c           
!c           'geometry shape factor'
!c           3.0d0
!c           'scaling factor'
!c           0.4d0
!c           'effective diffusion path length'
!c           0.01d0
!c           'effective hydraulic conductivity'
!c           1.0d-4
!c           'effective diffusion coefficient'
!c           0.5d-4
!c           'fracture proportion'
!c           0.5d0
!c           'interface of matrix and fracture in y-direction'
!c           0.5d0
!c           'done'
!c ----------------------------------------------------------------------


      logical :: dual_permeability
      
      real*8  :: beta_dp
      real*8  :: gamma_dp
      real*8  :: dist_dp   
      real*8  :: cond_ex_sat
      real*8  :: w_fracture   
      real*8  :: w_matrix 
      real*8  :: diff_eff_dp
      real*8  :: diff_eff_g_dp
      real*8  :: mat_frac_face_y
      
      real*8  :: tor_corr_a_ex
      real*8  :: tor_corr_b_ex
      
!c ----------------------------------------------------------------------

      end module dual
        