!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 355 $
!> $Author: dsu $
!> $Date: 2015-07-10 14:10:57 -0700 (Fri, 10 Jul 2015) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/fluxvs_dp.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c real*8 function fluxvs_dp
!c -------------------------
!c
!c compute water flux for dual permeability formulation
!c including exchange terms (variably saturated conditions)
!c sacrifice y-axis for exchange terms 
!c
!c written by:      Uli Mayer - July 17, 12
!c
!c last modified:
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   real*8:
!c           ------- 
!c           hhead_i            = hydraulic head in control volume i  + -
!c                                currently considered
!c           hhead_j            = hydraulic head in control volume j  + -
!c           psi_i              = pressure head in control volume i   + -
!c           psi_j              = pressure head in control volume j   + - 
!c           relperm_i          = relative permeability in control    + -
!c                                volume i
!c           relperm_j          = relative permeability in control    + -
!c                                volume j
!c           cinfvs             = influence coefficient               + -
!c           yg_i               = spatial coordinate in y-direction   + -
!c                                for ivol
!c           yg_j               = spatial coordinate in y-direction   + -
!c                                for jvol
!c           fluxvs             = water flux at interface             * +
!c 
!c           logical:
!c           --------
!c           upstream           = .true.  -> upstream weighting of    + -
!c                                           relative permeabilities 
!c           character:
!c           ----------
!c           iups               = upstream pointer                    + -
!c
!c common:   -
!c           
!c local:    real*8:
!c           -------
!c           rhalf              = constant
!c
!c external: -
!c ----------------------------------------------------------------------

      real*8 function fluxvs_dp(upstream,hhead_i,hhead_j,psi_i,psi_j,  &
                                relperm_i,relperm_j,iups,cinfvs,       &
                                yg_i,yg_j)
 
      use dual, only : alpha_dp_fixed, mat_frac_face_y
      
      implicit none
      
      external soilparm_ex
      
      !passed variables
      logical upstream
      character*1 iups
      real*8 :: hhead_i,hhead_j,psi_i,psi_j,relperm_i,relperm_j,cinfvs,&
                yg_i,yg_j
      
      !parameters
      real*8, parameter :: rhalf = 0.5d0, tiny = 1.0d-10
      
      !local variables
      real*8 :: relperm, relperm_ex_i, relperm_ex_j
      
!c  calculate exchange terms - y-dimension

!cmj_dp      if (yg_i.ne.yg_j) then
      !if (dabs(yg_i-yg_j).gt.tiny) then
      if((yg_i > mat_frac_face_y .and. yg_j < mat_frac_face_y) .or.                        &
          (yg_i < mat_frac_face_y .and. yg_j > mat_frac_face_y)) then
        
        relperm_ex_i = relperm_i
        relperm_ex_j = relperm_j
        call soilparm_ex(psi_i,relperm_ex_i)
        call soilparm_ex(psi_j,relperm_ex_j)
        relperm = (relperm_ex_i+relperm_ex_j)*rhalf
                
!c  compute exchange flux (y-direction)
!c  #### add replacement for influence coefficient
!        
!cummj fluxvs_dp = alpha_dp_fixed*relperm*(hhead_j-hhead_i)
!cummj !!!!!!calculate influnce coefficinet as cvol(ivol) + cvol(jvol) 
!cummj = total volume of dp medium
!cummj !!!!!!!!!! DOUBLE CHECK THIS !!!!!!!!!!!!
        fluxvs_dp = cinfvs*alpha_dp_fixed*relperm*(hhead_j-hhead_i)

!cxx   write(*,*) 'y-direction'
!cxx   write(*,*) relperm, alpha_dp_fixed, hhead_j, hhead_i
!        
!c  calculate fluxes in preferential flow and matrix regions

      else
      
!c  upstream or centered weighting for relative permeabilities

        if (upstream) then                         !upstream weighting
          if (iups.eq.'i') then
            relperm = relperm_i
          elseif (iups.eq.'j') then
            relperm = relperm_j
          end if
        else                                       !centered weighting
          relperm = (relperm_i+relperm_j)*rhalf
        end if

!c  compute interfacial flux in preferantial flow and matrix regions 
!c (x and z-directions)

        fluxvs_dp = relperm*cinfvs*(hhead_j-hhead_i)
!cxx  write(*,*) relperm, cinfvs, hhead_j, hhead_i  
      end if
       
      
!cmj_dp       write(*,*) yg_i, yg_j, 'fluxvs_dp', fluxvs_dp
!cmj_dp      pause    
!cxx  write(*,*) fluxvs_dp
      return
      end

