!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 301 $
!> $Author: dsu $
!> $Date: 2015-04-30 11:28:32 -0700 (Thu, 30 Apr 2015) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/fluxv_vl_dp.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c real*8 function fluxv_vl_dp
!c ------------------------
!c
!c compute advective mass flux for dual-permeability
!c
!c written by:      Mehrnoush Javadi - November 13, 12
!c
!c last modified:   -
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   real*8:
!c           -------
!c           totc_i             = total aqueous component             + -
!c                                concentration in control volume i
!c           totc_j             = total aqueous component             + -
!c                                concentration in control volume j
!c           cinfrt_v           = influence coeffcient for            + -
!c                                advective flux
!c           fluxv_vl           = advective flux                      * +
!c
!c           integer*4:
!c           ----------
!c           i                  = pointer to control volume i         + -
!c           j                  = pointer to control volume j         + -
!c           ic                 = pointer to current component        + -
!c
!c
!c gen.f:    real*8:
!c           -------
!c           totcnew(n,nn)      = total aqueous component             + -
!c                                concentrations
!c                                - new time level [moles/l water]
!c
!c           integer*4:
!c           ----------
!c           i2up               = pointer to control volume i2up      + -
!c                                (second upstream point), 
!c                                i2up = 0 -> second upstream point 
!c                                does not exist
!c
!c           character:
!c           ----------
!c           spatial_weighting  = 'upstream' -> upstream weigthing    + -
!c                                'centered' -> centered weighting
!c                                'vanleer' -> Van Leer flux limiter
!c                                              (upstream-downstream)
!c                                'vanleer2' -> Van Leer flux limiter
!c                                              (upstream-centered)
!c
!c common:   -
!c
!c local:    real*8:
!c           -------
!c           eps              = constant
!c           r0               = constant
!c           r1               = constant
!c           r2               = constant
!c           rhalf            = constant
!c           rquarter         = constant
!c           theta_r_ij       = Van Leer flux limiter
!c           r_ij             = smoothness sensor for Van Leer flux
!c                              limiter
!c           totc_dwn         = total aqueous component concentration
!c                              at downstream control volume
!c           totc_ij          = total aqueous component concentration
!c                              at for flux computation at interface
!c           totc_ups         = total aqueous component concentration
!c                              at upstream control volume
!c
!c external: -  
!c ----------------------------------------------------------------------
 
      real*8 function fluxv_vl_dp(totc_i,totc_j,i,j,cinfrt_v,ic)
 
      implicit none
      
      !passed variables
      real*8 :: totc_i,totc_j, cinfrt_v
      integer :: i, j, ic
      
      !parameters
      real*8, parameter :: r0 = 0.0d0
      
      !local variables
      real*8 :: totc_ij

!cmj_dp  added fluxvs_dp as an external function-Mehrnoush-21/11/2012
!cmj_dp  external fluxvs_dp

      
!c  upstream weigthing 

!cmj_dp      if (spatial_weighting.eq.'upstream') then

      if (cinfrt_v.gt.r0) then
          totc_ij = totc_i
      else
          totc_ij = totc_j
      end if
        
!cmj_dp      end if
!cmj_dp      write(*,*) cinfrt_v
!cmj_dp      write(*,*) totc_i
!cmj_dp      write(*,*) totc_j
!cmj_dp      write(*,*) totc_ij
!cmj_dp      pause


!c  compute advective flux
!cmj_dp  compute advective flux for dual-permeability-13/11/2012
!
!cmj_dp  fluxv_vl_dp = cinfrt_v * totc_ij
!cmj_dp  fluxv_vl_dp = fluxvs_dp(upstream,hhead_i,hhead_j,psi_i,psi_j,
!cmj_dp  &                          relperm_i,relperm_j,iups,cinfvs,
!cmj_dp  &                          yg_i,yg_j) * totc_ij
!                   
!
!cmj_dp  calculate exchange terms - y-diemnsion
!
!cmj_dp  if (yg_i.ne.yg_j) then
!      
!      
!cmj_dp  else  
      
      fluxv_vl_dp = cinfrt_v * totc_ij


!cmj_dp      write (*,*) cinfrt_v
!cmj_dp      write (*,*) totc_ij
!cmj_dp      write (*,*) 'fluxv_vl_dp', fluxv_vl_dp
!cmj_dp      pause
!cmj_dp      write(igsc,'(100e15.7)') xg(ivol),yg(ivol),zout,
!cmj_dp     &                            (cnew(ic,ivol),ic=1,nc-1),
!cmj_dp     &                            (cx(ix,ivol),ix=1,nxout)
!        
!cmj_dp  endif
 
      return
      end
