!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 268 $
!> $Author: dsu $
!> $Date: 2015-01-09 17:00:41 -0800 (Fri, 09 Jan 2015) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/seepface.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c real*8 function fluxd_g_dp
!c ---------------------
!c
!c compute dispersive/diffusive mass flux for dual-permeability
!c
!c written by:       Mengqi Jia, Nov 2021
!c
!c last modified:
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   real*8:
!c           -------
!c           totc_i             = total aqueous component             + -
!c                                concentration in control volume i
!c           totc_j             = total aqueous component             + -
!c                                concentration in control volume j
!c           cinfrt_d           = influence coefficient               + -
!c                                (hydrodynamic dispersion)
!c           fluxd              = dispersive flux                     * +
!c
!c common:   -
!c
!c local:    - 
!c
!c external: -
!c 
!c note: this function only work if there are 2 volumes in y direction 
!c and one is at yg=0.
!c ----------------------------------------------------------------------
 
      real*8 function fluxd_g_dp(totg_i,totg_j,cinfrt_d,cinfvs,pornew_i, &
                                 sgnew_i, pornew_j,sgnew_j,yg_i,yg_j)
      
      use dual
      
      implicit none
      
      !passed variables
      real*8 :: totg_i, totg_j, cinfrt_d, cinfvs, pornew_i, sgnew_i,   &
                pornew_j, sgnew_j, yg_i, yg_j
      
      real*8, parameter :: rhalf = 0.5d0, tiny = 1.0d-10, r1 = 1.0d0
      
      !local variables
      real*8 :: pornew_ex, sgnew_ex 
      
      
      if((yg_i > mat_frac_face_y .and. yg_j < mat_frac_face_y) .or.    &
         (yg_i < mat_frac_face_y .and. yg_j > mat_frac_face_y)) then

         if (yg_i.lt.tiny) then       !i is the matrix and j is fracture  
         
            pornew_ex = pornew_j    
            sgnew_ex = sgnew_j 
            
         elseif (yg_j.lt.tiny) then   !j is the matrix and i is the fracture
         
            pornew_ex = pornew_i
            sgnew_ex = sgnew_i
      
         end if
         
        fluxd_g_dp = sgnew_ex*pornew_ex *                                &
                     alpha_g_dp_fixed*cinfvs*(totg_j-totg_i)*            &
                     (sgnew_ex**tor_corr_b_ex)*(pornew_ex**(tor_corr_a_ex+r1))
      
      else
         
        fluxd_g_dp = cinfrt_d * (totg_j - totg_i)
         
      end if

      return
      end