!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 268 $
!> $Author: dsu $
!> $Date: 2015-01-09 17:00:41 -0800 (Fri, 09 Jan 2015) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/seepface.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c real*8 function fluxd
!c ---------------------
!c
!c compute dispersive/diffusive mass flux for dual-permeability
!c
!c written by:       UM-MJ- January 07, 2013
!c
!c last modified:
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   real*8:
!c           -------
!c           totc_i             = total aqueous component             + -
!c                                concentration in control volume i
!c           totc_j             = total aqueous component             + -
!c                                concentration in control volume j
!c           cinfrt_d           = influence coefficient               + -
!c                                (hydrodynamic dispersion)
!c           fluxd              = dispersive flux                     * +
!c
!c common:   -
!c
!c local:    - 
!c
!c external: -
!c 
!c note: this function only work if there are 2 volumes in y direction 
!c and one is at yg=0.
!c ----------------------------------------------------------------------
 
      real*8 function fluxd_dp(totc_i,totc_j,cinfrt_d,cinfvs,pornew_i, &
                               sanew_i, pornew_j,sanew_j,yg_i,yg_j)
      
      use dual
      
      implicit none
      
      !passed variables
      real*8 :: totc_i, totc_j, cinfrt_d, cinfvs, pornew_i, sanew_i,   &
                pornew_j, sanew_j, yg_i, yg_j
      
      real*8, parameter :: rhalf = 0.5d0, tiny = 1.0d-10
      
      !local variables
      real*8 :: pornew_ex, sanew_ex 
      
!cmj_dp  external diffcoff
!cmj_dp  logical tortuosity_corr    
!cmj_dp  real*8 diffcoff    
!cmj_dp  local variables
!cmj_dp  real*8 diff_eff_dp, diffav_dp, satav_dp, porav_dp     
!cmj_dp  diff_eff_dp =diffcoff(diffav_dp,satav_dp,porav_dp,tortuosity_corr) 
!cmj_dp  added diffusive flux equation based on Gerke and van Genuchten (1996) paper-Mehrnoush-08/01/2013    
!cmj_dp  calculate exchange terms - y-diemnsion
!
!cmj_dp      if (yg_i.ne.yg_j) then
!      
!      
!c      do a=0,nvz
!            
!cc        if (((yg_i .and. yg_j) .ge. 0) .and. 
!cc     &      ((yg_i .and. yg_j) .lt. 2.4)) then
!     
!cc            fluxd_dp = cinfrt_d * (totc_j - totc_i)
!            
!            
!            
!            
!cc        elseif (((yg_i .and. yg_j) .gt. 3.6) .and. 
!cc     &          ((yg_i .and. yg_j) .le. 6)) then
!        
!cc            fluxd_dp = cinfrt_d * (totc_j - totc_i)
!            
!cc        else
!cc            fluxd_dp = sanew_ex*pornew_ex  
!cc     &            *alpha_s_dp_fixed*cinfvs*(totc_j-totc_i)
!        
!cc        end if
!cc      end do
     
      
      if((yg_i > mat_frac_face_y .and. yg_j < mat_frac_face_y) .or.    &
          (yg_i < mat_frac_face_y .and. yg_j > mat_frac_face_y)) then

         if (yg_i.lt.tiny) then       !i is the matrix and j is fracture  
         
!cmj_dp  weighting of pornew and sanew for future work - Mehrnoush - 15/02/2013
            pornew_ex = pornew_j    
            sanew_ex = sanew_j 
            
     
         elseif (yg_j.lt.tiny) then   !j is the matrix and i is the fracture
         
            pornew_ex = pornew_i      
            sanew_ex = sanew_i
      
!cmj_dp  pornew_ex = (pornew_ex_i+pornew_ex_j)*rhalf
!cmj_dp  sanew_ex = (sanew_ex_i+sanew_ex_j)*rhalf
         
         
         end if 
         
        fluxd_dp = sanew_ex*pornew_ex *                                &
                   alpha_s_dp_fixed*cinfvs*(totc_j-totc_i)
        
!*********cdsu  test******************
!         if (totc_j > totc_i) then
!         
!           pornew_ex = pornew_i    
!           sanew_ex = sanew_i
!        
!         else
!         
!           pornew_ex = pornew_j      
!           sanew_ex = sanew_j
!                       
!         end if             
!            
!         fluxd_dp = sanew_ex*pornew_ex *                               &
!                    alpha_s_dp_fixed*cinfvs*(totc_j-totc_i)
!
!*********cdsu  test******************         
      
      else
         
        fluxd_dp = cinfrt_d * (totc_j - totc_i)            
         
      end if
      
!cmj_dp  write (*,*) yg_i, yg_j, sanew_ex_j
!cmj_dp  write (*,*) yg_i, yg_j, pornew_ex_j
!cmj_dp        write (*,*) yg_i, yg_j, alpha_s_dp_fixed
!cmj_dp  write (*,*) yg_i, yg_j, cinfvs
!cmj_dp  write (*,*) yg_i, yg_j, totc_j
!cmj_dp  write (*,*) yg_i, yg_j, totc_i
!cmj_dp        write (*,*) yg_i, yg_j, 'fluxd_dp', fluxd_dp
!cmj_dp  write (*,*) yg_i, yg_j, cinfrt_d
!cmj_dp        pause
      
      return
      end

!cmj_dp  sanew(ivol)* por  
