!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 355 $
!> $Author: dsu $
!> $Date: 2015-07-10 14:10:57 -0700 (Fri, 10 Jul 2015) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/initdualperm.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine initdualperm
!c -------------------
!c
!c physical parameters for dual permeability
!c
!c written by:      Danyang Su - Jul 09, 2015
!c
!c note: These codes are converted from Mehrnoush Javadi's 
!c       hardwired codes. Now the parameters can be read or
!c       calculated from input file.
!c      
!c last modified:   
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   -
!c
!c common: 
!c dual.F90:   -
!c           real*8:
!c           -------
!c           beta_dp            = shape factor [-] that depends on    + +
!c                                the geometry,  e.g., 3.0d0
!c           gamma_dp           = scaling factor [-] obtained by      + +
!c                                matching the results of the 
!c                                first-order approach at the 
!c                                half-time level of the cumulative 
!c                                infiltration curve to the numerical
!c                                solution of the horizontal 
!c                                infiltration equation 
!c                                [Gerke and van Genuchten, 1993]
!c                                e.g., 0.4
!c           dist_dp            = effective 'diffusion'               + +
!c                                pathlength [m]
!c                                e.g., half the matrix width or 
!c                                half the fracture spacing, 0.01 m
!c           cond_ex_sat        = effective hydraulic conductivity    + + 
!c                                [m/day], e.g., 1.0d-4 m/day
!c           w_fracture         = fracture proportion [-]             + +
!c                                e.g., 0.5
!c           w_matrix           = matrix proportion [-]               * +
!c                                equal to 1- w_fracture
!c                                e.g., 0.5
!c           diff_eff_dp        = effective 'diffusion' coefficient   + +
!c                                [m*m/day], e.g., 0.5d-4 m*m/day
!c           mat_frac_face_y    = interface of matrix and fracture    + +
!c                                location in y-direction [m]
!c                                e.g., 0.5 m
!c
!c gen.f:    real*8:
!c           -------
!c           integer*4:
!c           ----------
!c           icnv               = unit number, data conversion and    + -
!c                                             temporary storage
!c           idat               = unit number, run specific input     + -
!c                                             file
!c           igen               = unit number, generic output file    + -
!c           ilog               = unit number, logbook                + -
!c           itmp               = unit number, temporary storage      + -
!c
!c
!c
!c local:    real*8:
!c           -------
!c           r1                 = constant
!c           tiny               = small increment
!c
!c           integer*4:
!c           ----------
!c           ivol               = counter (control volumes)
!c           l_string           = length of text string

!c           logical:
!c           --------
!c           found_section      = .true.  -> section header was
!c                                           found in input file
!c           found_subsection   = .true.  -> subsection header was
!c                                           found in input file
!c
!c           character:
!c           ----------
!c           subsection         = name of subsection in input file
!c
!c external: findstrg  = find text string in file
!c           findzone  = find zone in input section
!c           readbloc  = read section of input file and write to
!c                       temporary file
!c ----------------------------------------------------------------------
 
      subroutine initdualperm
 
        use gen
        use dual

#ifdef PETSC
        use petsc_mpi_common, only : petsc_mpi_finalize
#endif
      
        implicit none
#ifdef PETSC
#include <finclude/petscsys.h>
#endif
      
      
        
        external findstrg, readbloc
        
        logical :: found_section, found_subsection
        character*72 :: sectionheader, subsection, strbuffer
        integer :: i
        
        real*8, parameter :: r1 = 1.0d0, r2 = 2.0d0
        
        sectionheader = 'physical parameters - dual permeability'
        call readbloc (idat,itmp,sectionheader,found_section,.true.)
      
!c  terminate program if section header not found
        if (.not.found_section) then
          goto 996
        end if

!c  write physical parameters for porous medium to generic output file
        if (b_enable_output .and. b_enable_output_gen) then
          write(igen,'(/72a)')('-',i=1,72)
          write(igen,'(a)') trim(sectionheader)
          write(igen,'(72a/)')('-',i=1,72)
        end if


!c  read physical parameters for dual permeability
        subsection = 'geometry shape factor'
        call findstrg(subsection,itmp,found_subsection)
        if (found_subsection) then
          read(itmp,*,err=998,end=998) beta_dp
          if (b_enable_output .and. b_enable_output_gen) then
            write(igen,'(a,1pe10.3,1x,a)')                             &
                  'geometry shape factor beta_dp                   = ',&
                  beta_dp, '[-]'
          end if
        else
          goto 997
        end if

        subsection = 'scaling factor'
        call findstrg(subsection,itmp,found_subsection)
        if (found_subsection) then
          read(itmp,*,err=998,end=998) gamma_dp
          if (b_enable_output .and. b_enable_output_gen) then
            write(igen,'(a,1pe10.3,1x,a)')                             &
                  'scaling factor gamma_dp                         = ',&
                  gamma_dp, '[-]'
          end if
        else
          goto 997
        end if
        
        subsection = 'effective diffusion path length'
        call findstrg(subsection,itmp,found_subsection)
        if (found_subsection) then
          read(itmp,*,err=998,end=998) dist_dp
          if (b_enable_output .and. b_enable_output_gen) then
            write(igen,'(a,1pe10.3,1x,a)')                             &
                  'effective diffusion path length dist_dp         = ',&
                  dist_dp, '[m]'
          end if
        else
          goto 997
        end if
        
        subsection = 'effective hydraulic conductivity'
        call findstrg(subsection,itmp,found_subsection)
        if (found_subsection) then
          read(itmp,*,err=998,end=998) cond_ex_sat
          if (b_enable_output .and. b_enable_output_gen) then
            write(igen,'(a,1pe10.3,1x,a)')                             &
                  'effective hydraulic conductivity cond_ex_sat    = ',&
                  cond_ex_sat, '[m/day]'
          end if
        else
          goto 997
        end if
        
        subsection = 'effective diffusion coefficient'
        call findstrg(subsection,itmp,found_subsection)
        if (found_subsection) then
          read(itmp,*,err=998,end=998) diff_eff_dp
          if (b_enable_output .and. b_enable_output_gen) then
            write(igen,'(a,1pe10.3,1x,a)')                             &
                  'effective diffusion coefficient diff_eff_dp     = ',&
                  diff_eff_dp, '[m^2/day]'
          end if
        else
          goto 997
        end if
        
        subsection = 'free phase gas diffusion coefficient'
        call findstrg(subsection,itmp,found_subsection)
        if (found_subsection) then
          read(itmp,*,err=998,end=998) diff_eff_g_dp
          if (b_enable_output .and. b_enable_output_gen) then
            write(igen,'(a,1pe10.3,1x,a)')                             &
                  'free phase gas diffusion coefficient diff_eff_g_dp     = ',&
                  diff_eff_g_dp, '[m^2/day]'
          end if
        else
          goto 997
        end if
        
        subsection = 'tortuosity parameters'
        call findstrg(subsection,itmp,found_subsection)
        if (found_subsection) then
          read(itmp,*,err=998,end=998) tor_corr_a_ex
          read(itmp,*,err=998,end=998) tor_corr_b_ex
          if (b_enable_output .and. b_enable_output_gen) then
            write(igen,'(a,1pe10.3,1x,a)')                             &
                  'tortuosity parameters = ',&
                  tor_corr_a_ex, '[-]'
          end if
        else
          goto 997
        end if
        
        subsection = 'fracture proportion'
        call findstrg(subsection,itmp,found_subsection)
        if (found_subsection) then
          read(itmp,*,err=998,end=998) w_fracture
          if (b_enable_output .and. b_enable_output_gen) then
            write(igen,'(a,1pe10.3,1x,a)')                             &
                  'fracture proportion w_fracture                  = ',&
                  w_fracture, '[-]'
          end if
        else
          goto 997
        end if
        
        subsection = 'interface of matrix and fracture in y-direction'
        call findstrg(subsection,itmp,found_subsection)
        if (found_subsection) then
          read(itmp,*,err=998,end=998) mat_frac_face_y
          if (b_enable_output .and. b_enable_output_gen) then
            write(igen,'(a,1pe10.3,1x,a)')                             &
                  'interface of matrix and fracture in y-direction = ',&
                  mat_frac_face_y, '[m]'
          end if
        else
          goto 997
        end if
        
        w_matrix = r1 - w_fracture
        alpha_dp_fixed = beta_dp * cond_ex_sat * gamma_dp/dist_dp**r2
        alpha_s_dp_fixed = beta_dp*w_matrix* diff_eff_dp /dist_dp**r2
        alpha_g_dp_fixed = beta_dp*w_matrix* diff_eff_g_dp /dist_dp**r2
        
        return
        
!c  terminate program if section header not found
996     continue
        if (rank == 0) then  
          write(ilog,*) 'SIMULATION TERMINATED'
          write(ilog,*) 'error reading input file'
          write(ilog,*) 'section "',trim(sectionheader),'" missing'
          close(ilog)
        end if
#ifdef PETSC
        call petsc_mpi_finalize
#endif
        stop
        
997     continue
        if (rank == 0) then  
          write(ilog,*) 'SIMULATION TERMINATED'
          write(ilog,*) 'error reading input file'
          write(ilog,*) 'parameter "',trim(subsection),'" missing'
          close(ilog)
        end if
#ifdef PETSC
        call petsc_mpi_finalize
#endif
        stop

998     continue
        backspace(itmp)
        read(itmp,'(a)') strbuffer
        if (rank == 0) then
          write(ilog,*) 'SIMULATION TERMINATED'
          write(ilog,'(2a)') 'error reading in itmp data: ',trim(strbuffer)
          write(*,*) 'SIMULATION TERMINATED'
          write(*,'(2a)') 'error reading in itmp data: ',trim(strbuffer)
          close(ilog)
        end if
#ifdef PETSC
        call petsc_mpi_finalize
#endif  
        stop      

      end
