!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 544 $
!> $Author: dsu $
!> $Date: 2017-11-25 12:43:55 -0800 (Sat, 25 Nov 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/initcpice.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine initcpgs
!c -------------------
!c
!c control parameters for ice loading/unloading
!c ported from Sergio Bea's code by Danyang Su
!c
!c written by:      Danyang Su - Oct 22, 17
!c
!c last modified:   
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c 
!c                                                                    I O
!c passed:   -
!c
!c common:   
!c gen.f:    integer*4:
!c           ----------
!c           idat               = unit number, run specific input     + -
!c                                             file
!c           igen               = unit number, generic output file    + -
!c           ilog               = unit number, log book               + -
!c           itmp               = unit number, temporary storage      + -
!c           l_time_unit        = length of time_unit for output      * +
!c
!c           logical:
!c           --------
!c           fully_saturated    = .true.  -> saturated conditions     * +
!c           geo_chemistry      = .true.  -> local or background and  * +
!c                                           source chemistry
!c           reactive_transport = .true.  -> perform reactive         * +
!c                                           transport simulation
!c           steady_flow        = .true.  -> steady state flow        * +
!c           transient_flow     = .true.  -> .not.steady_flow,        * +
!c                                        -> transient flow
!c           variably_saturated = .true.  -> .not.fully_saturated,    * +
!c                                        -> variably saturated
!c                                           conditions
!c           varsat_flow        = .true.  -> perform flow simulation  * +
!c
!c           character:
!c           ----------
!c           problem_title      = problem title                       * +
!c           section_header     = section header                      * +
!c           drive              = drive of program installation       * +
!c           time_unit          = time unit for output -> 'years'     * +
!c                                                        'days'
!c                                                        'hours'
!c                                                'seconds'
!c dens.f:   logical:
!c           --------
!c           density_dependence = .true.  -> density-dependant flow 
!c
!c local:    integer*4:
!c           ----------
!c           l_string           = length of text string
!c
!c           logical:
!c           --------
!c           found_section      = .true.  -> section header was
!c                                           found in input file
!c           found_subsection   = .true.  -> subsection header was
!c                                           found in input file
!c
!c           character:
!c           ----------
!c           subsection         = name of subsection in input file
!c
!c
!c external: readbloc  = read section of input file and write to
!c                       temporary file
!c ----------------------------------------------------------------------
 
      subroutine initcpice
 
      use parm
      use gen
      use dens
#ifdef PETSC
      use petsc_mpi_common, only : petsc_mpi_finalize
#endif

      implicit none
      
      integer :: i, l_string

      external readbloc
 
      logical found_section, found_subsection,iserror
      character*72 subsection

!c  read numerical data and write to temporary file   
   
      section_header = 'ice sheet loading/unloading' 
      call readbloc (idat,itmp,section_header,found_section,.true.)

      if (.not. found_section) then
        goto 999
      end if
    
!cprovi---------------------------------------------------
!cprovi---------------------------------------------------
!cprovi---------------------------------------------------    
!cprovi---------------------------------------------------
!cprovi Compute Ice Sheet loading  
!cprovi---------------------------------------------------
      compute_permafrost = .false. 

      icestage = -1
      nicestages = -1

      allocate (ice_sheet)
      call create_ (ice_sheet)
      call read_ice_sheet_block_ (ice_sheet,itmp,heat_transport,       &
                                  icetimeline, iserror)
      if (iserror) then
        if (rank == 0) then 
          write(*,*) 'Error when call service read_ice_sheet_block_'
          write(ilog,*) 'Error when call service read_ice_sheet_block_'
          close(ilog)
        end if
#ifdef PETSC
        call petsc_mpi_finalize
#endif
        stop 
      end if
        
      if (b_enable_output .and. b_enable_output_gen) then
        write(igen,*) 'Ice Sheet loading/unloading is computed'
      end if
        
      subsection = 'compute permafrost'
      call findstrg(subsection,itmp,found_subsection)
      if (found_subsection) then
        if (b_enable_output .and. b_enable_output_gen) then  
          write(igen,*) 'Permafrost is considered'
        end if
        compute_permafrost=.true.          
      end if 
      if (b_enable_output .and. b_enable_output_gen) then
        call write_ (ice_sheet,igen,iserror)
      end if
      if (iserror) then
        if (rank == 0) then  
          write(*,*) 'Error when call service write_'
          write(ilog,*) 'Error when call service write_'
          close(ilog)
        end if
#ifdef PETSC
        call petsc_mpi_finalize
#endif
        stop 
      end if

      goto 1000

999   continue
      if (rank == 0) then
        write(ilog,*) 'error reading input file'
        write(ilog,*) 'section "',section_header(:l_string),'"'
        close(ilog)
      end if
#ifdef PETSC
      call petsc_mpi_finalize
#endif
      stop

1000  return
      end
