!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 268 $
!> $Author: dsu $
!> $Date: 2015-01-09 17:00:41 -0800 (Fri, 09 Jan 2015) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/mem_hmcd.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c -----------------------------------------------------------------------
!c subroutine mem_hmcd
!c ----------------- 
!c M. Xie (April 2014)
!c
!c ----------------------------------------------------------------------
  
      subroutine mem_hmcd
       
      use parm
      use gen, only : f_epor_ps, f_etau_ps, f_epor_ss, f_etau_ss
      use chem, only : nc, nx
      use phys, only : nzn
      
      implicit none

      external checkerr
      INTEGER*4 ierr,ilog
      
      
 
!cprovi-----------------------------------------------------------
!cprovi Allocate variables corresponding to evaporation processes 
!cprovi----------------------------------------------------------- 

     
      allocate (f_epor_ps(nc,nzn), stat = ierr)
        f_epor_ps=1.0d0 
      call checkerr(ierr,'f_epor_ps',ilog)    

      allocate (f_etau_ps(nc,nzn), stat = ierr)
        f_etau_ps=1.0d0 
      call checkerr(ierr,'f_etau_ps',ilog)    

      allocate (f_epor_ss(nx,nzn), stat = ierr)
          f_epor_ss=1.0d0 
      call checkerr(ierr,'f_epor_ss',ilog) 
      
        allocate (f_etau_ss(nx,nzn), stat = ierr)
          f_etau_ss=1.0d0 
      call checkerr(ierr,'f_etau_ss',ilog)    


      return
      end
