!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 268 $
!> $Author: dsu $
!> $Date: 2015-01-09 17:00:41 -0800 (Fri, 09 Jan 2015) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/rootwat.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c -----------------------------------------------------------------------
!c real*8 function rootwat
!c -----------------------
!c compute root water uptake for current control volume 
!c
!c written by:      Uli Mayer - July 24, 01
!c
!c last modified:   Uli Mayer - Nov. 28, 01
!c                  updated calculation of root water uptake
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   real*8:
!c           -------
!c           satwnew            = aqueous phase satutaion             + -
!c                                - new time level
!c
!c           integer*4:
!c           ----------
!c           izn                = pointer to material property zone   + -
!c
!c          
!c common:   
!c phys.f:   real*8:
!c           ------- 
!c           satwlim(nzn)       = water saturation at wilting point   + -
!c           satwfield(nzn)     = water saturation at field capacity  + -
!c           rew0(izn)          = relative extractable water at       + -
!c                                50% of maximum extraction capacity 
!c                                (fitting parameter)
!c           p1(nzn)            = fitting parameter for root water    + -
!c                                uptake function
!c           tree_trans_factor(nzn) = tree transpiration factor       + -
!c
!c
!c local:    rew                = relative extractable water
!c           r0                 = constant
!c           r1                 = constant
!c           r2                 = constant
!c
!c
!c external: -
!c ----------------------------------------------------------------------
 
      real*8 function rootwat(satwnew,izn)
 
      use parm
      use phys

      implicit none

      real*8 :: satwnew
      
      integer :: izn
      
      real*8, parameter :: r0 = 0.0d0, r1 = 1.0d0, r2 = 2.0d0
      
      real*8 :: rew

      rew = dmin1((satwnew-satwlim(izn))                              &
     &            /(satwfield(izn)-satwlim(izn)),r1)
    
    if (satwnew.gt.satwlim(izn)) then                                
        rootwat = rew**r2*dexp(p1(izn)*rew)/                          &
     &            (rew0(izn)**r2*dexp(p1(izn)*rew0(izn))              &
     &           + rew**r2*dexp(p1(izn)*rew))/tree_trans_factor(1)
    else
        rootwat = r0
      end if

    return
      end
