!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 599 $
!> $Author: dsu $
!> $Date: 2018-08-08 09:47:15 -0700 (Wed, 08 Aug 2018) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/soilparm_ex.F90 $
!---------------------------------------------------------------------
!********************************************************************!
    
!c ----------------------------------------------------------------------
!c subroutine soilparm_ex
!c ----------------------
!c
!c compute soil hydraulic parameters for exchange term 
!c (variably saturated flow)
!c
!c written by:      Uli Mayer - July 17, 12
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   real*8:
!c           -------
!c           uvsnew             = pressure head (new time level)      + -
!c           relperm            = relative permeability               * + 
!c
!c local:    real*8:
!c           -------
!c           r1                 = constant
!c           sanew_ex           = saturation
!c           swr_ex             = residual saturation                 
!c           spalpha_ex         = soil hydraulic function parameter   
!c           spbeta_ex          = soil hydraulic function parameter   
!c           spgamma_ex         = soil hydraulic function parameter   
!c           expn_ex            = krw - p equation exponent           
!c           aentry_ex          = air entry pressure set to 0
!c
!c           integer*4:
!c           ----------
!c
!c external: satfpres  = compute saturations from pressure
!c           relpfsat  = compute relative permeability from saturation
!c ----------------------------------------------------------------------
 
      subroutine soilparm_ex(uvsnew,relperm)
 
      implicit none

      external relpfsat, satfpres
      
      real*8 :: uvsnew,relperm
      
      real*8 :: relpfsat, satfpres

!c  check aentry_ex value
      
      real*8, parameter :: r1 = 1.0d0, aentry_ex = 0.0d0
      
!c   local variables 
      real*8 :: swr_ex, spalpha_ex, spbeta_ex, spgamma_ex, expn_ex,    &
                sanew_ex

!c  temporary - hardwired parameters

      swr_ex = 0.232d0                         !unitless
      spalpha_ex = 1.9d0                       !m-1
      spbeta_ex = 1.31d0                       !unitless
      spgamma_ex = r1 - (r1 / spbeta_ex)       !unitless
      expn_ex = 0.5d0                          !unitless

!c  compute soil hydraulic parameters for exchange term 

      sanew_ex = satfpres(swr_ex,aentry_ex,uvsnew,                     &
     &                    spalpha_ex,spbeta_ex,spgamma_ex)
      relperm = relpfsat(sanew_ex,swr_ex,expn_ex,spgamma_ex)
!cbad      write(23,*) 'sanew_ex = ', sanew_ex, 'relperm = ',relperm
      
      return
      end
