!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 545 $
!> $Author: dsu $
!> $Date: 2017-11-27 17:15:52 -0800 (Mon, 27 Nov 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/tprfvs_faceflux.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine tprfvs
!c -----------------
!c
!c write transient data of interface flux for variably saturated flow 
!c simulation to output file
!c
!c written by:      Danyang Su - Nov 27, 2017
!c
!c last modified:   -
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c   
!c                                                                    I O
!c
!c passed:   integer*4:
!c           ----------
!c           ivol               = pointer to current control volume   + -
!c           jvol               = pointer to current control volume   + -
!c
!c common:
!c gen.f:    real*8:
!c           -------
!c
!c           logical:
!c           --------
!c
!c
!c local:    real*8:
!c           ------- 
!c
!c 
!c --------------------------------------------------------------------------

      subroutine tprfvs_faceflux(ivol,jvol,igb,ngb_tstep)
 
      use gen, only : fully_saturated, upstream, ngb_vol_ijface_jtemp, &                      
                      hhead, uvsnew, relperm, cinfvs, xg, yg, zg,      &
                      nfloatbit, realbuffer_gb, igfvel, offset_igfvel, &
                      ngb_vol_ijface_area, offset_igfvel_ijk,          &
                      ngb_vol_ijface_velratio, time_io,                &
                      b_output_trans_binary
      use dual, only : dual_permeability
      use module_binary_mpiio, only : binary_write_data

      implicit none
#ifdef PETSC_V3_6_X
#include <petsc/finclude/petscsys.h>
#elif PETSC
#include <finclude/petscsys.h>
#endif
      
      integer :: ivol, jvol, igb, ngb_tstep
      
      !c local variables
      integer :: i1sav, nvars
      real*8 :: vel, velx, vely, velz, dflux
      character*1 :: iups   
      real*8, parameter :: r1 = 1.0d0      
      real*8 :: fluxfs, fluxvs, fluxvs_dp
      external fluxfs, fluxvs, fluxvs_dp
      

      i1sav = ngb_vol_ijface_jtemp(igb)

!c compute flux along the control volume interface
      if (.not.fully_saturated) then
        if (upstream) then
          iups = 'i'                            !h_i >= h_j
          if (hhead(jvol).gt.hhead(ivol)) then  !h_j > h_i
            iups = 'j'
          end if
        end if
      
        if (.not.dual_permeability) then
          dflux = - fluxvs(upstream,hhead(ivol),                       &
                           hhead(jvol),relperm(ivol),                  &
                           relperm(jvol),iups,                         &
                           cinfvs(i1sav))                              
        else                                                           
          dflux = - fluxvs_dp(upstream,hhead(ivol),                    &
                              hhead(jvol),uvsnew(ivol),                &
                              uvsnew(jvol),relperm(ivol),              &
                              relperm(jvol),iups,                      &
                              cinfvs(i1sav),                           &
                              yg(ivol),yg(jvol))
        end if
                                                             
      elseif (fully_saturated) then 
                                                             
        dflux = - fluxfs(uvsnew(ivol),uvsnew(jvol),cinfvs(i1sav))
      end if
      
      
!c  velocity is the flux (m^3/day) divided
!c  by the interfacial area between the two control volumes
!c  this is darcy velocity, not the linear groundwater velocity, for the later one,
!c  the velocity should be divided by the porosity, averaged by adjacent vols (DSU, 2017-08-02)
      vel = dflux / ngb_vol_ijface_area(igb)
      velx = vel*ngb_vol_ijface_velratio(1,igb)
      vely = vel*ngb_vol_ijface_velratio(2,igb)
      velz = vel*ngb_vol_ijface_velratio(3,igb)

!c  write data back to file
      if (b_output_trans_binary) then
        nvars = 4 
        realbuffer_gb(1:nvars)= (/time_io,velx,vely,velz/)
        
        call binary_write_data(igfvel(igb), 1, (/ngb_tstep/),          &
                    offset_igfvel_ijk(igb),.true.)
        call binary_write_data(igfvel(igb), nvars, realbuffer_gb,      &
                    offset_igfvel(igb),.true.) 

        offset_igfvel(igb) = offset_igfvel(igb) + nvars*nfloatbit
      else
        write(igfvel(igb),'(4e15.6e3)') time_io,velx,vely,velz
      end if

      return
      end subroutine tprfvs_faceflux
