!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 544 $
!> $Author: dsu $
!> $Date: 2017-11-25 12:43:55 -0800 (Sat, 25 Nov 2017) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/tprfvs.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine tprfvs
!c -----------------
!c
!c write transient data for variably saturated flow simulation to output
!c file
!c
!c written by:      Uli Mayer - July 27, 01
!c
!c last modified:   -
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c   
!c                                                                    I O
!c
!c passed:   integer*4:
!c           ----------
!c           ivol               = pointer to current control volume   + -
!c
!c common:
!c gen.f:    real*8:
!c           -------
!c           cvol(nn)           = nodal volumes                       + -
!c           hhead(nn)          = hydraulic head                      + -
!c           pornew(nn)         = porosity (new time level)           + -
!c           sgnew(nn)          = gaseous phase saturation            + - 
!c                                - new time level
!c           sanew(nn)          = aqueous phase saturation            + - 
!c                                - new time level
!c           time_io            = current solution time (I/O units)   + -
!c           uvsnew(nn)         = solution vector (new time level)    + -
!c           zg(nn)             = spatial coordinates in z-direction  + -
!c
!c           integer*4:
!c           ----------
!c           igbp               = unit number, flow variables,        + -
!c                                transient data
!c           mpropvs(nn)        = pointer array for allocation of     + -
!c                                material properties
!c           mtime              = current time step                   + -
!c           nn                 = number of control volumes           + -
!c
!c           logical:
!c           --------
!c           fully_saturated    = .true.  -> saturated conditions     + -
!c           root_uptake        = .true.  -> compute root water       + -
!c                                           uptake 
!c           variably_saturated = .true.  -> .not.fully_saturated,    + -
!c                                        -> variably saturated
!c                                           conditions
!c
!c
!c local:    real*8:
!c           ------- 
!c           phead              = pressure head
!c           qroot              = root water uptake for current
!c                                control volume
!c           theta_a            = aqueous phase content         
!c           theta_g            = gas phase content         
!c           r1                 = constant
!c
!c external: rootwat   = compute rate of root water uptake
!c --------------------------------------------------------------------------

      subroutine tprfvs(ivol,igb,ngb_tstep)
 
      use parm
      use gen
      use phys
      use module_binary_mpiio, only : binary_write_data

      implicit none
#ifdef PETSC_V3_6_X
#include <petsc/finclude/petscsys.h>
#elif PETSC
#include <finclude/petscsys.h>
#endif
      
      integer :: ivol, igb, ngb_tstep
      
      real*8 :: theta_a, theta_g, qroot, rootwat, phead

      external rootwat

      real*8, parameter :: r1 = 1.0d0
      
      integer :: nvarsigbp
#ifdef MPI
      integer(kind=MPI_OFFSET_KIND) :: offset
#else
      integer*8 :: offset
#endif

!c     write(*,'(/a)') 'enter routine tprfvs ...'

      theta_a = pornew(ivol)*sanew(ivol)

!c  compute root uptake rate

      if (root_uptake) then
          qroot = cvol(ivol) * rootwat(sanew(ivol),mpropvs(ivol))
      else
          qroot = 0.0d0
      end if

      if (fully_saturated) then

        hhead(ivol) = uvsnew(ivol)
        phead = uvsnew(ivol) - zg(ivol)
        
        if (b_output_trans_binary) then
          nvarsigbp = 5 
          realbuffer_gb(1:nvarsigbp)= (/time_io,hhead(ivol),           &
                                 phead,sanew(ivol),theta_a/)
        else
          write(igbp,'(5e15.6e3)') time_io,hhead(ivol),                &
                                 phead,sanew(ivol),theta_a
        end if
                                                                       
      elseif (variably_saturated) then
                                                                       
        hhead(ivol) = uvsnew(ivol)+zg(ivol)                            
        sgnew(ivol) = r1 - sanew(ivol)                                 
        theta_g = pornew(ivol)*sgnew(ivol)  
        
        if (b_output_trans_binary) then
          nvarsigbp = 8 
          realbuffer_gb(1:nvarsigbp)= (/time_io,hhead(ivol),           &
                                 uvsnew(ivol),sanew(ivol),theta_a,     &
                                 sgnew(ivol), theta_g, qroot/)
        else
          write(igbp,'(8e15.6e3)') time_io,hhead(ivol),                &
                                 uvsnew(ivol),sanew(ivol),theta_a,     &
                                 sgnew(ivol), theta_g, qroot 
        end if
        
      end if
      
      if (b_output_trans_binary) then
        call binary_write_data(igbp_mpi(igb), 1, (/ngb_tstep/),&
                     offset_igbp_ijk(igb),.true.)
        call binary_write_data(igbp_mpi(igb), nvarsigbp,       &
                     realbuffer_gb,offset_igbp(igb),.true.) 

        offset_igbp(igb) = offset_igbp(igb) + nvarsigbp*nfloatbit

      end if
      
!#ifdef DEBUG
!      if(ivol == 14) then
!          write(idbg,*) "-->tprfvs hhead(ivol)", hhead(ivol)
!      end if
!#endif

      return
      end
