!*****Revision Informations Automatically Generated by VisualSVN*****!
!---------------------------------------------------------------------
!> $ID:$
!> $Revision: 305 $
!> $Author: dsu $
!> $Date: 2015-05-04 15:37:44 -0700 (Mon, 04 May 2015) $
!> $URL: https://biot.eos.ubc.ca/svn/min3p_thcm/branches/dsu_dual_permeability/src/min3p/tstepfs.F90 $
!---------------------------------------------------------------------
!********************************************************************!

!c ----------------------------------------------------------------------
!c subroutine tstepfs
!c ------------------
!c
!c estimate magnitude of next time step (full saturated flow)
!c
!c written by:      Danyang Su - April, 2015
!c
!c last modified:   
!c
!c definition of variables:
!c
!c I --> on input   * arbitrary  - initialized  + entries expected
!c O --> on output  * arbitrary  - unaltered    + altered
!c                                                                    I O
!c passed:   -
!c
!c common:
!c gen.f:    real*8:
!c           -------
!c           delt               = time step                           + -
!c           delt_vs            = estimated time step                 * +
!c                                (variably saturated flow)
!c           deltmax            = maximum time step                   + -
!c           deltmin            = minimum time step                   + -
!c           saold(nn)          = aqueous phase saturation            + -
!c                                - old time level
!c           sanew(nn)          = aqueous phase saturation            + -
!c                                - new time level
!c           sw_star            = anticipated change in saturation    + -
!c                                per time step
!c           integer*4:
!c           ----------
!c           nn                 = total number of control volumes     + -
!c
!c local:    real*8:
!c           -------
!c           delta_sw           = saturation change
!c           r0                 = constant
!c           rhalf              = constant 
!c           r5                 = constant
!c
!c           integer*4:
!c           ----------
!c           ivol               = counter (control volumes)
!c
!c external: -
!c ----------------------------------------------------------------------

      subroutine tstepfs

      use gen

      implicit none

!c  new time step estimate for variably saturated flow
      delt_vs = delt_vs*2.0d0      
      delt_vs = dmin1(delt_vs, deltmax)         !lower bound - min. time step

      return
      end
